# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'localhost:4444'
    needs: build
    steps: 
      - name: Build with Maven
        run: echo deploy dev

  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: 'localhost:4444'
    needs: deploy-dev
    steps: 
      - name: Run a one line script
        run: echo deploy hmg

  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: 'localhost:4444'
    needs: deploy-hmg
    steps: 
      - name: Run a one line script
        run: echo deploy prd
    
  
  
  
